title: SharifiX Tech Blog
description: A bilingual blog on networking, cybersecurity, SEO, AI, and cloud.
baseurl: "" 
url: "https://sharifiXblog.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed
